on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "!docs/**"

jobs:
  test:
    name: Run existing tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install package
        run: pip install ".[all]"
      - name: Run Kafka
        uses: spicyparrot/kafka-kraft-action@v1.1.3
        with:
          kafka-version: "3.6.1"
          kafka-topics: "test_bluesky_raw_docs,1"
      - name: Run pytest
        run: pytest -vvv
